name: Integración Continua - Práctica 4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Detección de cambios (Git)
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para que SonarCloud analice el historial

      # 2. Preparación del entorno
      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      # 3 y 4. Compilación, Tests (JUnit) y Análisis de Calidad (SonarCloud)
      - name: Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token automático de GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # El secreto que guardaste antes
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=ggarcia75_practica4-calidad \
          -Dsonar.organization=ggarcia75 \
          -Dsonar.host.url=https://sonarcloud.io

      # 5. Publicación del Artefacto (Solo si todo lo anterior funciona)
      - name: Subir Artefacto (JAR)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: aplicacion-nominas
          path: target/*.jar
          retention-days: 5
